#include "sdkconfig.h"

#define FLEXISPOT_UART_NUM      CONFIG_FLEXISPOT_UART_NUM
#define FLEXISPOT_TXD_PIN       CONFIG_FLEXISPOT_TXD_PIN
#define FLEXISPOT_RXD_PIN       CONFIG_FLEXISPOT_RXD_PIN
#define FLEXISPOT_DETECT_PIN    CONFIG_FLEXISPOT_DETECT_PIN
#define FLEXISPOT_TASK_STACK_SIZE 4096
#define FLEXISPOT_TASK_PRIORITY 10
